name: pupilica_hackathon
description: "A new Pupilica Hackathon project."


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.8
  device_frame: ^1.4.0
  osmea_components:
    git:
      url: https://github.com/masterfabric-mobile/osmea.git
      path: packages/components

  # Navigation
  go_router: ^16.2.1

  # State Management
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^8.2.0
  injectable: ^2.5.1

  # Internationalization
  slang: ^4.8.1

  # File System & Paths
  path: ^1.9.1
  path_provider: ^2.1.5

  # OCR & Image Processing
  flutter_tesseract_ocr: ^0.4.29
  
  # File Picker & Document Handling
  file_picker: ^8.0.0+1
  image_picker: ^1.0.7
  file_saver: ^0.2.3
  
  # PDF Processing
  pdf: ^3.10.7
  pdf_text: ^0.5.0
  open_file: ^3.3.2
  
  # Image Processing
  image: ^4.1.7
  
  # File Handling
  mime: ^1.0.5
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Sharing
  share_plus: ^7.2.2


dev_dependencies:
  # Flutter Testing
  flutter_test:
    sdk: flutter

  # Code Generation
  injectable_generator: ^2.8.1
  build_runner: ^2.7.1
  slang_build_runner: ^4.8.1
  flutter_gen_runner: any

  # Linting & Code Quality
  flutter_lints: ^5.0.0

  # App Icons
  flutter_launcher_icons: ^0.13.1


flutter:

  uses-material-design: true

  assets:
    - assets/tessdata/
    - assets/tessdata_config.json
    - assets/images/

# Flutter Launcher Icons Configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app-logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/app-logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/app-logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/app-logo.png"
