name: pupilica_hackathon
description: "A new Pupilica Hackathon project."


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.8
  device_frame: ^1.4.0
  osmea_components:
    git:
      url: https://github.com/masterfabric-mobile/osmea.git
      path: packages/components

  # Navigation
  go_router: ^16.2.1

  # State Management
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0

  # Dependency Injection
  get_it: ^8.2.0
  injectable: ^2.5.1

  # Internationalization
  slang: ^4.8.1

  # File System & Paths
  path: ^1.9.1
  path_provider: ^2.1.5

  # OCR & Image Processing
  flutter_tesseract_ocr: ^0.4.29


dev_dependencies:
  # Flutter Testing
  flutter_test:
    sdk: flutter

  # Code Generation
  injectable_generator: ^2.8.1
  build_runner: ^2.7.1
  slang_build_runner: ^4.8.1
  flutter_gen_runner: any

  # Linting & Code Quality
  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true
